# Generated by Django 3.0.8 on 2020-08-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('metaTitle', models.CharField(max_length=400)),
                ('slug', models.SlugField(max_length=100)),
                ('summary', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('publishedAt', models.DateTimeField(auto_now=True)),
                ('hitcounts', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
