# Generated by Django 3.0.8 on 2020-08-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200805_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userip',
            name='hitcounts',
        ),
        migrations.CreateModel(
            name='Hitcounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hitcounts', models.PositiveIntegerField(default=0)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
