# Generated by Django 3.0.8 on 2020-08-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PER', 'Personal'), ('WEB', 'Web-Development'), ('DSA', 'Data Structures & Algorithms')], default='WEB', max_length=3)),
                ('slug', models.SlugField(max_length=100)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
